# Generated by Django 6.0.7 on 2026-07-31 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidhaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_la_bidhaa', models.CharField(max_length=200)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bei_ya_kununulia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bei_ya_kuuzia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idadi_stoo', models.IntegerField(default=0)),
                ('maelekezo_maalum', models.TextField(blank=True, null=True)),
                ('tarehe_iliyoingia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bidhaa',
                'verbose_name_plural': 'Bidhaa',
            },
        ),
        migrations.CreateModel(
            name='Mteja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majina_kamili', models.CharField(max_length=200)),
                ('namba_ya_simu', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('tarehe_ya_kusajiliwa', models.DateTimeField(auto_now_add=True)),
                ('aina', models.CharField(default='binafsi', max_length=50)),
                ('pre_order_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Mteja',
                'verbose_name_plural': 'Wateja',
            },
        ),
        migrations.CreateModel(
            name='VochaYaDuka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_la_duka', models.CharField(default='TradeCore Main Store', max_length=100)),
                ('salio_la_sms', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vocha ya Duka',
                'verbose_name_plural': 'Vocha za Duka',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitendo', models.CharField(max_length=255)),
                ('aina', models.CharField(default='kawaida', max_length=50)),
                ('muda', models.DateTimeField(auto_now_add=True)),
                ('mhusika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-muda'],
            },
        ),
        migrations.CreateModel(
            name='Duka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_la_duka', models.CharField(blank=True, max_length=150, null=True)),
                ('anwani_au_mahali', models.CharField(blank=True, max_length=150, null=True)),
                ('mwenye_duka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duka', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duka',
                'verbose_name_plural': 'Maduka',
            },
        ),
        migrations.CreateModel(
            name='Mauzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idadi', models.IntegerField(default=1)),
                ('bei_ya_kuuzia_stoo', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('punguzo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jumla_pesa_iliyopokelewa', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('tarehe_ya_mauzo', models.DateTimeField(auto_now_add=True)),
                ('bidhaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.bidhaa')),
                ('muuzaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mteja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.mteja')),
            ],
            options={
                'verbose_name': 'Mauzo',
                'verbose_name_plural': 'Mauzo',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni_admin', models.BooleanField(default=False, verbose_name='Bosi Mkuu (Admin)')),
                ('ni_cashier', models.BooleanField(default=True, verbose_name='Mhudumu wa Kaunta')),
                ('ni_stoo', models.BooleanField(default=False, verbose_name='Msimamizi wa Stoo')),
                ('picha', models.ImageField(blank=True, null=True, upload_to='wafanyakazi/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
