# Generated by Django 6.0.7 on 2026-07-31 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MzigoUlioingia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tarehe', models.DateTimeField(auto_now_add=True)),
                ('bidhaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.bidhaa')),
            ],
        ),
    ]
