# Generated by Django 6.0.7 on 2026-07-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='muda_wa_mwisho',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
