# Generated by Django 6.0.7 on 2026-08-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bidhaa',
            name='picha',
            field=models.ImageField(blank=True, null=True, upload_to='bidhaa/'),
        ),
        migrations.AddField(
            model_name='mauzo',
            name='aina_ya_ongezeko',
            field=models.CharField(choices=[('TZS', 'TZS (Pesa)'), ('PERCENT', 'Asilimia (%)')], default='TZS', max_length=10),
        ),
        migrations.AddField(
            model_name='mauzo',
            name='aina_ya_punguzo',
            field=models.CharField(choices=[('TZS', 'TZS (Pesa)'), ('PERCENT', 'Asilimia (%)')], default='TZS', max_length=10),
        ),
        migrations.AddField(
            model_name='mauzo',
            name='namba_ya_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mauzo',
            name='njia_ya_malipo',
            field=models.CharField(choices=[('CASH', 'Cash (Pesa Mkononi)'), ('MPESA', 'M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTELMONEY', 'Airtel Money'), ('BANK', 'Bank Transfer / Kadi')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='mauzo',
            name='ongezeko',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mauzo',
            name='bei_ya_kuuzia_stoo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='mauzo',
            name='jumla_pesa_iliyopokelewa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bidhaa',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.kategoria'),
        ),
    ]
