# Generated by Django 6.0.7 on 2026-08-14 13:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_kategoria_bidhaa_picha_mauzo_aina_ya_ongezeko_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-muda'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='bidhaa',
            options={'ordering': ['jina_la_bidhaa'], 'verbose_name': 'Bidhaa', 'verbose_name_plural': 'Bidhaa'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'ordering': ['jina'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Makategoria'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Login History', 'verbose_name_plural': 'Login Histories'},
        ),
        migrations.AlterModelOptions(
            name='mauzo',
            options={'ordering': ['-tarehe_ya_mauzo'], 'verbose_name': 'Mauzo', 'verbose_name_plural': 'Mauzo'},
        ),
        migrations.AlterModelOptions(
            name='mteja',
            options={'ordering': ['majina_kamili'], 'verbose_name': 'Mteja', 'verbose_name_plural': 'Wateja'},
        ),
        migrations.AlterModelOptions(
            name='mzigoulioingia',
            options={'ordering': ['-tarehe'], 'verbose_name': 'Mzigo Uliingia (GRN)', 'verbose_name_plural': 'Mizigo Iliyoingia (GRN)'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='mhusika',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidhaa',
            name='bei_ya_kununulia',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='bidhaa',
            name='bei_ya_kuuzia',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='bidhaa',
            name='idadi_stoo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bidhaa',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidhaa', to='pos_app.kategoria'),
        ),
        migrations.AlterField(
            model_name='mauzo',
            name='bidhaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mauzo', to='pos_app.bidhaa'),
        ),
        migrations.AlterField(
            model_name='mauzo',
            name='idadi',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mauzo',
            name='mteja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mauzo', to='pos_app.mteja'),
        ),
        migrations.AlterField(
            model_name='mauzo',
            name='muuzaji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mauzo_aliyofanya', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mteja',
            name='pre_order_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mzigoulioingia',
            name='bidhaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mizigo_iliyoingia', to='pos_app.bidhaa'),
        ),
        migrations.AlterField(
            model_name='mzigoulioingia',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mzigoulioingia',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vochayaduka',
            name='salio_la_sms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_department', models.CharField(default='Stoo', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PURCHASE_REQUEST', 'Purchase Request'), ('LOW_STOCK', 'Low Stock'), ('SALE', 'Sale'), ('STOCK', 'Stock'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=30)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pos_app.purchaserequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidhaa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='pos_app.bidhaa')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_app.purchaserequest')),
            ],
            options={
                'verbose_name': 'Purchase Request Item',
                'verbose_name_plural': 'Purchase Request Items',
            },
        ),
    ]
