# Generated by Django 6.0.7 on 2026-08-14 17:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_alter_activitylog_options_alter_bidhaa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matumizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fuel', 'Fuel'), ('Transport', 'Transport'), ('Salary', 'Salary'), ('Maintenance', 'Maintenance'), ('Electricity', 'Electricity'), ('Internet', 'Internet'), ('Meal', 'Meal'), ('Others', 'Others')], db_index=True, default='Others', max_length=50)),
                ('maelezo', models.TextField(max_length=1000)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('kiasi', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], db_index=True, default='PAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matumizi_aliyosajili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matumizi',
                'verbose_name_plural': 'Matumizi',
                'ordering': ['-created_at'],
            },
        ),
    ]
