# Generated by Django 6.0.7 on 2026-08-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0009_salereturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mteja',
            options={},
        ),
        migrations.AddField(
            model_name='mteja',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
