# Generated by Django 6.0.7 on 2026-08-17 13:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0011_communicationlog_customercampaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mteja',
            options={'ordering': ['majina_kamili'], 'verbose_name': 'Mteja', 'verbose_name_plural': 'Wateja'},
        ),
        migrations.AddField(
            model_name='duka',
            name='currency',
            field=models.CharField(default='TZS', max_length=10),
        ),
        migrations.AddField(
            model_name='duka',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='duka',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='maduka/logos/'),
        ),
        migrations.AddField(
            model_name='duka',
            name='receipt_footer',
            field=models.CharField(blank=True, default='Asante kwa kufanya manunuzi nasi!', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='duka',
            name='simu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='duka',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='duka',
            name='terminal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='duka',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mteja',
            name='anwani',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mteja',
            name='eneo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mteja',
            name='marketing_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mteja',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
