# Generated by Django 6.0.7 on 2026-08-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0013_bidhaa_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidhaa',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='bidhaa',
            name='barcode_aina',
        ),
    ]
