# Generated by Django 6.0.7 on 2026-09-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0014_remove_bidhaa_barcode_remove_bidhaa_barcode_aina'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaa',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Barcode ya Bidhaa'),
        ),
    ]
