# Generated by Django 6.0.7 on 2026-09-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0015_bidhaa_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='duka',
            name='business_type',
            field=models.CharField(choices=[('FASHION', 'Fashion & Clothing'), ('COMPUTERS', 'Computers & Electronics'), ('SUPERMARKET', 'Supermarket / Grocery'), ('COSMETICS', 'Cosmetics & Beauty'), ('PHARMACY', 'Pharmacy / Health Shop'), ('HARDWARE', 'Hardware & Building Materials'), ('RESTAURANT', 'Restaurant / Food'), ('STATIONERY', 'Stationery & Bookshop'), ('PHONES', 'Mobile Phones & Accessories'), ('AUTOPARTS', 'Auto Parts'), ('FURNITURE', 'Furniture & Home'), ('GENERAL', 'General Retail')], db_index=True, default='GENERAL', max_length=30, verbose_name='Aina ya Biashara'),
        ),
        migrations.AddField(
            model_name='kategoria',
            name='business_type',
            field=models.CharField(choices=[('FASHION', 'Fashion & Clothing'), ('COMPUTERS', 'Computers & Electronics'), ('SUPERMARKET', 'Supermarket / Grocery'), ('COSMETICS', 'Cosmetics & Beauty'), ('PHARMACY', 'Pharmacy / Health Shop'), ('HARDWARE', 'Hardware & Building Materials'), ('RESTAURANT', 'Restaurant / Food'), ('STATIONERY', 'Stationery & Bookshop'), ('PHONES', 'Mobile Phones & Accessories'), ('AUTOPARTS', 'Auto Parts'), ('FURNITURE', 'Furniture & Home'), ('GENERAL', 'General Retail')], db_index=True, default='GENERAL', max_length=30, verbose_name='Aina ya Biashara'),
        ),
        migrations.AddField(
            model_name='kategoria',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='jina',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='kategoria',
            constraint=models.UniqueConstraint(fields=('business_type', 'jina'), name='uniq_tradecore_category_type_name'),
        ),
    ]
