# Generated by Django 6.0.7 on 2026-09-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0016_duka_business_type_kategoria_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhaa',
            name='jina_la_bidhaa',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mteja',
            name='majina_kamili',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mteja',
            name='namba_ya_simu',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
