# Generated by Django 6.0.7 on 2026-09-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0017_alter_bidhaa_jina_la_bidhaa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ruhusa_matumizi',
            field=models.BooleanField(default=False, verbose_name='Ruhusa ya Matumizi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruhusa_mauzo',
            field=models.BooleanField(default=False, verbose_name='Ruhusa ya Mauzo (POS)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruhusa_mawasiliano',
            field=models.BooleanField(default=False, verbose_name='Ruhusa ya Mawasiliano'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruhusa_ripoti',
            field=models.BooleanField(default=False, verbose_name='Ruhusa ya Ripoti'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruhusa_stoo',
            field=models.BooleanField(default=False, verbose_name='Ruhusa ya Stoo na Bidhaa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruhusa_wateja',
            field=models.BooleanField(default=False, verbose_name='Ruhusa ya Wateja'),
        ),
    ]
