# Generated by Django 6.0.7 on 2026-09-26 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0018_profile_ruhusa_matumizi_profile_ruhusa_mauzo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='duka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wafanyakazi', to='pos_app.duka'),
        ),
    ]
