# Generated by Django 6.0.7 on 2026-09-29 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0020_inventory_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='pos_app_sto_duka_id_351541_idx',
            old_name='stockmov_duka_prod_created',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='pos_app_sto_duka_id_c875c6_idx',
            old_name='stockmov_duka_type_created',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
