# Generated by Django 6.0.7 on 2026-10-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0022_tenant_isolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vochayaduka',
            name='duka',
        ),
    ]
