# Generated by Django 6.0.7 on 2026-10-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0024_businesssubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='vochayaduka',
            name='duka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocha', to='pos_app.duka'),
        ),
    ]
