# Generated by Django 6.0.7 on 2026-10-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0025_vochayaduka_duka'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzo',
            name='bei_ya_kununulia_stoo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
