# Generated by Django 6.0.7 on 2026-10-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0029_premium_billing_months_pricing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='pos_app_pay_user_id_ac5e17_idx',
            old_name='pos_app_pay_user_id_2d5f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='pos_app_pay_gateway_fe27a9_idx',
            old_name='pos_app_pay_gate_4e3f3b_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='billing_months',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='unit_price',
        ),
    ]
